Unmodified Dag Wieers version. Modified Files: ChangeLog conglomerate.spec.in

diff --git a/conglomerate.spec.in b/conglomerate.spec.in
--- a/conglomerate.spec.in
+++ b/conglomerate.spec.in
@@ -1,62 +1,111 @@
-#
-# This "spec" file is for creating a rpm package.
-#
-%define name    conglomerate
-%define version @VERSION@
-%define release 1
-%define prefix  /usr
- 
-Summary:        Extensible XML Editor
-Name:           %{name}
-Version:        %{version}
-Release:        %{release}
-Copyright:      GPL
-Group:          Applications/Editors
-URL:            http://www.conglomerate.org/
-Vendor:         The Conglomerate Team <developers@conglomerate.org>
-Source:         %{name}-%{version}.tar.gz
-BuildRoot:      %{_tmppath}/%{name}-%{version}
- 
+# DarAuthority: dag
+# DarContact: Conglomerate Developers <conglomerate-devel@lists.copyleft.no>
+
+Summary: Information authoring, management, and transformation system.
+Name: conglomerate
+Version: 0.7.12
+Release: 0
+License: GPL
+Group: Applications/Text
+URL: http://www.conglomerate.org/
+
+Packager: Dag Wieers <dag@wieers.com>
+Vendor: Dag Apt Repository, http://dag.wieers.com/apt/
+
+Source: http://prdownloads.sourceforge.net/conglomerate/conglomerate-%{version}.tar.gz
+BuildRoot: %{_tmppath}/root-%{name}-%{version}
+Prefix: %{_prefix}
+
+BuildRequires: libxml2-devel >= 2.0, libgnomeui-devel >= 2.0, libglade2-devel >= 2.0
+BuildRequires: scrollkeeper
+
+Requires(post): scrollkeeper
+
 %description
-Conglomerate is a complete system for working with documents. It lets the user
-create, revise, archive, search, convert and publish information in several
-media, using a single source document.The system consists of a graphical
-frontend for all user operations, and a server/database which performs
-storage, searching, revision control, transformation and publishing.
- 
+Conglomerate is a project to create a complete structured information
+authoring, management, archival, revision control and transformation
+system. Conglomerate uses XML semantics and powerful graphical editing,
+coupled with a centralised storage model and a flexible transformation
+language to create an environment which is easy to use, produces high-
+quality structured output, and lets the user target several output media
+with a single source document.
+
 %prep
-%setup -q
- 
+%setup
+
+#### FIXME: Fix the intltool problem. (Please fix upstream)
+#%{__perl} -pi.orig -e 's|/home/david/jhbuilt/share/intltool|%{_datadir}/intltool|' intltool-merge.in
+
 %build
-export CXXFLAGS="${RPM_OPT_FLAGS}";
-./configure --prefix=%{prefix}
- 
-make
- 
+%configure \
+	--disable-schemas-install
+%{__make} %{?_smp_mflags}
+
 %install
-[ -d ${RPM_BUILD_ROOT} ] && rm -rf ${RPM_BUILD_ROOT};
-mkdir -p ${RPM_BUILD_ROOT}
-make prefix=${RPM_BUILD_ROOT}%{prefix} install-strip
- 
+%{__rm} -rf %{buildroot}
+export GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL="1"
+%makeinstall
+%find_lang %{name}
+
+### Clean up buildroot
+%{__rm} -rf %{buildroot}%{_localstatedir}/scrollkeeper/ 
+%{__rm} -f %{buildroot}%{_datadir}/pixmaps/ChangeLog
+
+%post
+scrollkeeper-update -q || :
+export GCONF_CONFIG_SOURCE="$(gconftool-2 --get-default-source)"
+gconftool-2 --makefile-install-rule %{_sysconfdir}/gconf/schemas/%{name}.schemas &>/dev/null
+
+%postun
+scrollkeeper-update -q || :
+
 %clean
-[ -d ${RPM_BUILD_ROOT} ] && rm -rf ${RPM_BUILD_ROOT};
- 
-%files
-%defattr(-,root,root)
-%doc AUTHORS BUGS COPYING ChangeLog INSTALL NEWS README TODO
- 
-%{prefix}/bin/conglomerate
-%{prefix}/share/*
-%{prefix}/var/*
+%{__rm} -rf %{buildroot}
+
+%files -f %{name}.lang
+%defattr(-, root, root, 0755)
+%doc AUTHORS BUGS ChangeLog COPYING NEWS README TODO
+%doc %{_datadir}/gnome/help/conglomerate/
+#%doc %{_datadir}/gtk-doc/html/conglomerate/
+%config %{_sysconfdir}/gconf/schemas/*.schemas
+%{_bindir}/*
+%{_datadir}/application-registry/*.applications
+%{_datadir}/applications/*.desktop
+%{_datadir}/conglomerate/
+%{_datadir}/mime-info/*
+%{_datadir}/omf/conglomerate/
+%{_datadir}/pixmaps/*.png
 
 %changelog
-* Wed Sept 3 2003 Sean Middleditch <elanthis@awesomeplay.com>
-- Version generated by ./configure.
+* Wed Feb 18 2004 Dag Wieers <dag@wieers.com> - 0.7.12-0
+- Updated to release 0.7.12.
 
-* Fri Aug 29 2003 Michael Rasmussen <mir@datanom.net> (0.7 release)
-- Updated to version 0.7.0
+* Tue Feb 03 2004 Dag Wieers <dag@wieers.com> - 0.7.11-0
+- Updated to release 0.7.11.
 
-* Sat Jun 06 2003 Michael Rasmussen <mir@datanom.net> (0.5.3 release)
-- First version of this spec file
+* Tue Jan 06 2004 Dag Wieers <dag@wieers.com> - 0.7.9-0
+- Updated to release 0.7.9.
 
-# end of file
+* Sat Dec 20 2003 Dag Wieers <dag@wieers.com> - 0.7.8-0
+- Updated to release 0.7.8.
+
+* Thu Oct 30 2003 Dag Wieers <dag@wieers.com> - 0.7.6-0
+- Updated to release 0.7.6.
+
+* Wed Oct 08 2003 Dag Wieers <dag@wieers.com> - 0.7.5-0
+- Updated to release 0.7.5.
+
+* Tue Sep 23 2003 Dag Wieers <dag@wieers.com> - 0.7.3-0
+- Updated to release 0.7.3.
+
+* Fri Sep 19 2003 Dag Wieers <dag@wieers.com> - 0.7.2-0
+- Updated to release 0.7.2.
+
+* Tue Sep 02 2003 Dag Wieers <dag@wieers.com> - 0.7.1-0
+- Updated to release 0.7.1.
+
+* Sat Aug 30 2003 Dag Wieers <dag@wieers.com> - 0.7.0-0
+- Updated to release 0.7.0.
+
+* Thu Jun 26 2003 Dag Wieers <dag@wieers.com> - 0.5.4-0
+- Initial package. (using DAR)
